---
- name: install nginx
  hosts: all
  become: yes
  tasks:
  - name: Installation
    apt:
      name: apache2
      update_cache: yes
      state: latest
  - name: service start
    service:
      name:apache2
      state: started
